blank_issues_enabled: false

contact_links:
  - name: ðŸ’¬ Questions & Discussions
    url: https://github.com/matteospanio/torchfx/discussions
    about: |
      Please use GitHub Discussions for questions, usage help,
      and open-ended discussions that are not bugs or feature requests.
